# Generated by Django 5.1.2 on 2024-12-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('rating', models.CharField(default='No rating', max_length=50)),
                ('price', models.CharField(default='NA', max_length=20)),
            ],
        ),
    ]
